### ISSUE TITLE
Extract Value With XPath Rule

### ISSUE THREAD

**Issue by jszod** [vmware-samples/cloud-suitability-analyzer#2]
### Why
So that values in XML files can be extracted during the analysis

As an analyzer
I want to find the value of elements specified by an XPath rule
So that I can extract values that are defined in XML files

**Scenario: specified xml element found**
**Given** and xpath value type rule exists
**And** the specified xml element exists in one of the analyzed files
**When** the rule is executed by CSA
**Then** the value of the xml element specified by the rule is added to the analysis findings

#### Notes

**Comment by chrisumbel** [comment]
I'll close this out after yaml
