### ISSUE TITLE
The docker-notEmpty rule incorrectly flags all SQL scripts that have a FROM clause

### ISSUE THREAD

**Issue by rwwilden** [vmware-samples/cloud-suitability-analyzer#28]
The docker-notEmpty rule generates _a lot of_ noise because it flags every SQL script that has a FROM clause as a low prio issue.

For example:
![afbeelding](https://user-images.githubusercontent.com/617960/97401098-7a6b4480-18f0-11eb-8b6e-b458b139e79b.png)

Unfortunately I'm not proficient enough with this rule syntax, otherwise I would have created a PR for this.

**Comment by stevew00ds** [comment]
Thank you for the feedback. We've decided to remove the rule. Will publish a new release shortly
