### ISSUE TITLE
Compare / Range Bound XPath Rule

### ISSUE THREAD

**Issue by jszod** [vmware-samples/cloud-suitability-analyzer#3]
#### Why
So that a range of values can be searched for in XML files

As an analyzer
I want to
So that

**Scenario: **
**Given**
**When**
**Then**

#### Notes
Use case examples:
* Is a value between 3 - 10

**Comment by chrisumbel** [comment]
If a document had a node like 

<TargetFramework>12.3.4</TargetFramework>

a rule could be written to find nodes less that "12.3.4" or between "12.0.0" and "12.3.4".  Note that semantic versions are strings and contain odd appendages like "-beta"
